### ISSUE TITLE
question for lighting and shading

### ISSUE THREAD

**Issue by iamxiaoyubei** [HinanawiTenshi/magic-house#1]
1.我们只考虑太阳光源(平行光)吗？
2.所有需要进行Lighting and shading的物体都是有贴图的吗？

**Comment by r0bertr** [comment]
@iamxiaoyubei
1. 暂时是
2. 是

**Comment by iamxiaoyubei** [comment]
Blinn-Phong不能够算是complex lighting吗？final project要求只能固定phong么？（因为里面写着Simple lighting and shading(phong)）

**Comment by iamxiaoyubei** [comment]
问题：
1. 太阳要不要显示出来？
2. 太阳光照要不要随着时间旋转（白天到天黑，按照时间转动）？
