### ISSUE TITLE
夜昼变换存在的问题

### ISSUE THREAD

**Issue by iamxiaoyubei** [HinanawiTenshi/magic-house#3]
1.  天空盒图像没有alpha通道，无法在着色器中调节，目前先暂时调颜色，会有问题
2.  我的太阳模型导入没有效果，不知道可否解决，是[太阳光线模型](https://www.cgtrader.com/free-3d-models/space/other/sun-with-rays-c4c1e5374435d1aa0d2026c6380bddb9)里面的这个模型
3. surburban house那个模型也导入会出问题，不知道为啥？是模型本身就有问题么？模型在资源文件夹中存在着，也可在[这里](https://www.cgtrader.com/items/39962/download-page)找到

**Comment by r0bertr** [comment]
1. 试试
```c
float alpha = 0.5f;
FragColor = vec4(texture(texture0, TexCoords).rgb, alpha);
```

2-3. 只有用图片作为材质的模型才能导入，用blender的和vray的暂时没有办法 @iamxiaoyubei

**Comment by iamxiaoyubei** [comment]
1. 这个还是不行

**Comment by r0bertr** [comment]
https://learnopengl-cn.github.io/04%20Advanced%20OpenGL/03%20Blending/
要显示alpha是要用blending的..你用了吗 @iamxiaoyubei

**Comment by iamxiaoyubei** [comment]
ok了
